version:  '3.9'

services: 
  vue:
    container_name: frontend
    build: 
      context: .
      dockerfile: dockerfile
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - '8081:8080'